version: '3.8'

services:
  nginx:
    container_name: deeplink-nginx
    image: nginx:latest
    ports:
      - '2222:2222'
    build:
    volumes:
      - '.:/usr/share/nginx/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    restart: always