version: '3.8'

services:
  deeplink-nginx:
    container_name: deeplink-nginx
    image: nginx:latest
    ports:
      - '3333:80'
    volumes:
      - './:/usr/share/nginx/html:ro'
      - './nginx.conf:/etc/nginx/conf.d/default.conf:ro'
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
