version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - '2222:2222'
    volumes:
      - '.:/usr/share/nginx/html'
      - './nginx.conf:/etc/nginx/conf.d/default.conf'
    restart: always