version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "2222:2222"
    volumes:
      - ./apple-app-site-association:/usr/share/nginx/html/apple-app-site-association
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
```
```yaml
server {
    listen 80;
    listen [::]:2222;

    root /usr/share/nginx/html;

    location /apple-app-site-association {
        default_type application/json;
    }

}